#!/usr/bin/env node

/**
 * Theme Generator Script
 *
 * Automatically generates tokens.css based on theme.config.js
 * Run: node packages/config/generate-theme.js
 * Or: pnpm generate:theme
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { themeConfig } from "./theme.config.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const { accent, gray, error, success, warning, radius, scaling, fontFamily } =
    themeConfig;

// Radius scale mapping
const radiusScales = {
    none: {
        1: "0px",
        2: "0px",
        3: "0px",
        4: "0px",
        5: "0px",
        6: "0px",
    },
    small: {
        1: "0.125rem", // 2px
        2: "0.25rem", // 4px
        3: "0.375rem", // 6px
        4: "0.5rem", // 8px
        5: "0.75rem", // 12px
        6: "1rem", // 16px
    },
    medium: {
        1: "0.25rem", // 4px
        2: "0.5rem", // 8px
        3: "0.75rem", // 12px
        4: "1rem", // 16px
        5: "1.5rem", // 24px
        6: "2rem", // 32px
    },
    large: {
        1: "0.375rem", // 6px
        2: "0.75rem", // 12px
        3: "1rem", // 16px
        4: "1.5rem", // 24px
        5: "2rem", // 32px
        6: "3rem", // 48px
    },
    full: {
        1: "0.5rem", // 8px
        2: "1rem", // 16px
        3: "1.5rem", // 24px
        4: "2rem", // 32px
        5: "3rem", // 48px
        6: "9999px", // Full rounded
    },
};

const currentRadiusScale = radiusScales[radius] || radiusScales.medium;

// Generate color scale mappings (1-12)
function generateScaleMappings(targetVar, sourceColor) {
    const steps = Array.from({ length: 12 }, (_, i) => i + 1);

    const solidMappings = steps
        .map(
            (step) =>
                `    --${targetVar}-${step}: var(--${sourceColor}-${step});`
        )
        .join("\n");

    const alphaMappings = steps
        .map(
            (step) =>
                `    --${targetVar}-a${step}: var(--${sourceColor}-a${step});`
        )
        .join("\n");

    return { solidMappings, alphaMappings };
}

// Generate the complete tokens.css content
function generateTokensCSS() {
    const grayMappings = generateScaleMappings("gray", gray);
    const accentMappings = generateScaleMappings("accent", accent);
    const errorMappings = generateScaleMappings("error", error);
    const successMappings = generateScaleMappings("success", success);
    const warningMappings = generateScaleMappings("warning", warning);

    return `/* ============================================
   RADIX UI COLORS - PRODUCTION COLOR SYSTEM
   ============================================
   
   This file is AUTO-GENERATED by generate-theme.js
   To change colors, edit theme.config.js and run:
   pnpm generate:theme
   
   Current Theme:
   - Accent: ${accent}
   - Gray: ${gray}
   - Error: ${error}
   - Success: ${success}
   - Warning: ${warning}
   - Radius: ${radius}
   - Scaling: ${scaling}
   ============================================ */

/* Import Radix Color Scales - Light Mode */
@import "@radix-ui/colors/${gray}.css";
@import "@radix-ui/colors/${accent}.css";
@import "@radix-ui/colors/${error}.css";
@import "@radix-ui/colors/${success}.css";
@import "@radix-ui/colors/${warning}.css";

/* Import Radix Alpha Variants - Light Mode */
@import "@radix-ui/colors/${gray}-alpha.css";
@import "@radix-ui/colors/${accent}-alpha.css";
@import "@radix-ui/colors/${error}-alpha.css";
@import "@radix-ui/colors/${success}-alpha.css";
@import "@radix-ui/colors/${warning}-alpha.css";

/* Import Radix Color Scales - Dark Mode */
@import "@radix-ui/colors/${gray}-dark.css";
@import "@radix-ui/colors/${accent}-dark.css";
@import "@radix-ui/colors/${error}-dark.css";
@import "@radix-ui/colors/${success}-dark.css";
@import "@radix-ui/colors/${warning}-dark.css";

/* Import Radix Alpha Variants - Dark Mode */
@import "@radix-ui/colors/${gray}-dark-alpha.css";
@import "@radix-ui/colors/${accent}-dark-alpha.css";
@import "@radix-ui/colors/${error}-dark-alpha.css";
@import "@radix-ui/colors/${success}-dark-alpha.css";
@import "@radix-ui/colors/${warning}-dark-alpha.css";

@layer base {
  :root {
    /* ============================================
       SCALING
       Global size multiplier
       ============================================ */
    --scaling: ${scaling};
    
    /* ============================================
       RADIUS SCALE - ${radius}
       6-step border radius scale
       ============================================ */
    --radius-1: ${currentRadiusScale[1]};
    --radius-2: ${currentRadiusScale[2]};
    --radius-3: ${currentRadiusScale[3]};
    --radius-4: ${currentRadiusScale[4]};
    --radius-5: ${currentRadiusScale[5]};
    --radius-6: ${currentRadiusScale[6]};
    
    /* Semantic radius tokens */
    --radius-sm: var(--radius-1);
    --radius-md: var(--radius-2);
    --radius-lg: var(--radius-3);
    --radius-xl: var(--radius-4);
    --radius-2xl: var(--radius-5);
    --radius-full: var(--radius-6);
    
    /* Legacy radius token (for backward compatibility) */
    --radius: var(--radius-2);

    /* ============================================
       GRAY SCALE (${gray}) - 12 Steps
       ============================================ */
${grayMappings.solidMappings}

    /* Gray Alpha Variants */
${grayMappings.alphaMappings}

    /* ============================================
       ACCENT SCALE (${accent}) - 12 Steps
       ============================================ */
${accentMappings.solidMappings}

    /* Accent Alpha Variants */
${accentMappings.alphaMappings}

    /* ============================================
       ERROR/DESTRUCTIVE SCALE (${error}) - 12 Steps
       ============================================ */
${errorMappings.solidMappings}

    /* Error Alpha Variants */
${errorMappings.alphaMappings}

    /* ============================================
       SUCCESS SCALE (${success}) - 12 Steps
       ============================================ */
${successMappings.solidMappings}

    /* Success Alpha Variants */
${successMappings.alphaMappings}

    /* ============================================
       WARNING SCALE (${warning}) - 12 Steps
       ============================================ */
${warningMappings.solidMappings}

    /* Warning Alpha Variants */
${warningMappings.alphaMappings}

    /* ============================================
       TYPOGRAPHY SYSTEM
       Production-grade type scale
       ============================================ */
    
    /* Font Families */
    --font-sans: ${fontFamily.sans || '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"'};
    --font-mono: ${fontFamily.mono || 'ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, "Liberation Mono", monospace'};
    
    /* Font Sizes - 9-step scale (Radix Themes compatible) */
    --font-size-1: calc(0.75rem * var(--scaling));    /* 12px */
    --font-size-2: calc(0.875rem * var(--scaling));   /* 14px */
    --font-size-3: calc(1rem * var(--scaling));       /* 16px - base */
    --font-size-4: calc(1.125rem * var(--scaling));   /* 18px */
    --font-size-5: calc(1.25rem * var(--scaling));    /* 20px */
    --font-size-6: calc(1.5rem * var(--scaling));     /* 24px */
    --font-size-7: calc(1.875rem * var(--scaling));   /* 30px */
    --font-size-8: calc(2.25rem * var(--scaling));    /* 36px */
    --font-size-9: calc(3rem * var(--scaling));       /* 48px */
    
    /* Line Heights */
    --line-height-1: calc(1rem * var(--scaling));     /* 16px */
    --line-height-2: calc(1.25rem * var(--scaling));  /* 20px */
    --line-height-3: calc(1.5rem * var(--scaling));   /* 24px */
    --line-height-4: calc(1.625rem * var(--scaling)); /* 26px */
    --line-height-5: calc(1.75rem * var(--scaling));  /* 28px */
    --line-height-6: calc(2rem * var(--scaling));     /* 32px */
    --line-height-7: calc(2.25rem * var(--scaling));  /* 36px */
    --line-height-8: calc(2.75rem * var(--scaling));  /* 44px */
    --line-height-9: calc(3.75rem * var(--scaling));  /* 60px */
    
    /* Letter Spacing */
    --letter-spacing-1: 0.0025em;
    --letter-spacing-2: 0em;
    --letter-spacing-3: 0em;
    --letter-spacing-4: -0.0025em;
    --letter-spacing-5: -0.005em;
    --letter-spacing-6: -0.00625em;
    --letter-spacing-7: -0.0075em;
    --letter-spacing-8: -0.01em;
    --letter-spacing-9: -0.025em;
    
    /* Font Weights */
    --font-weight-light: 300;
    --font-weight-regular: 400;
    --font-weight-medium: 500;
    --font-weight-semibold: 600;
    --font-weight-bold: 700;

    /* ============================================
       SEMANTIC TOKENS - Light Mode
       Mapped from Radix Color Scales
       ============================================ */
    
    /* Base Colors */
    --background: var(--gray-2);
    --foreground: var(--gray-12);
    
    /* Card/Surface */
    --card: var(--gray-2);
    --card-foreground: var(--gray-12);
    
    /* Popover/Dropdown */
    --popover: var(--gray-2);
    --popover-foreground: var(--gray-12);
    
    /* Primary (Accent) */
    --primary: var(--accent-9);
    --primary-hover: var(--accent-10);
    --primary-active: var(--accent-11);
    --primary-foreground: white;
    
    /* Secondary */
    --secondary: var(--gray-4);
    --secondary-hover: var(--gray-5);
    --secondary-foreground: var(--gray-12);
    
    /* Muted */
    --muted: var(--gray-4);
    --muted-hover: var(--gray-5);
    --muted-foreground: var(--gray-11);
    
    /* Accent (for hover states) */
    --accent: var(--accent-4);
    --accent-hover: var(--accent-5);
    --accent-foreground: var(--accent-11);
    
    /* Destructive */
    --destructive: var(--error-9);
    --destructive-hover: var(--error-10);
    --destructive-foreground: white;
    
    /* Borders */
    --border: var(--gray-7);
    --border-hover: var(--gray-8);
    
    /* Input */
    --input: var(--gray-8);
    --input-hover: var(--gray-9);
    
    /* Focus Ring */
    --ring: var(--accent-8);
    
    /* Overlay (Alpha) */
    --overlay: var(--gray-a8);
  }
  
  .dark {
    /* ============================================
       SEMANTIC TOKENS - Dark Mode
       Radix automatically switches to dark variants
       ============================================ */
    
    /* Base Colors */
    --background: var(--gray-1);
    --foreground: var(--gray-12);
    
    /* Card/Surface */
    --card: var(--gray-2);
    --card-foreground: var(--gray-12);
    
    /* Popover/Dropdown */
    --popover: var(--gray-2);
    --popover-foreground: var(--gray-12);
    
    /* Primary (Accent) */
    --primary: var(--accent-9);
    --primary-hover: var(--accent-10);
    --primary-active: var(--accent-11);
    --primary-foreground: white;
    
    /* Secondary */
    --secondary: var(--gray-3);
    --secondary-hover: var(--gray-4);
    --secondary-foreground: var(--gray-12);
    
    /* Muted */
    --muted: var(--gray-3);
    --muted-hover: var(--gray-4);
    --muted-foreground: var(--gray-11);
    
    /* Accent (for hover states) */
    --accent: var(--accent-3);
    --accent-hover: var(--accent-4);
    --accent-foreground: var(--accent-11);
    
    /* Destructive */
    --destructive: var(--error-9);
    --destructive-hover: var(--error-10);
    --destructive-foreground: white;
    
    /* Borders */
    --border: var(--gray-6);
    --border-hover: var(--gray-7);
    
    /* Input */
    --input: var(--gray-7);
    --input-hover: var(--gray-8);
    
    /* Focus Ring */
    --ring: var(--accent-8);
    
    /* Overlay (Alpha) */
    --overlay: var(--gray-a8);
  }
}
`;
}

// Main execution
try {
    const tokensContent = generateTokensCSS();
    const tokensPath = path.join(__dirname, "tokens.css");

    fs.writeFileSync(tokensPath, tokensContent, "utf-8");
} catch (_error) {
    process.exit(1);
}
