/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [],
  theme: {
    extend: {
      /* ============================================
         TYPOGRAPHY SYSTEM
         ============================================ */
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        1: ['var(--font-size-1)', { lineHeight: 'var(--line-height-1)', letterSpacing: 'var(--letter-spacing-1)' }],
        2: ['var(--font-size-2)', { lineHeight: 'var(--line-height-2)', letterSpacing: 'var(--letter-spacing-2)' }],
        3: ['var(--font-size-3)', { lineHeight: 'var(--line-height-3)', letterSpacing: 'var(--letter-spacing-3)' }],
        4: ['var(--font-size-4)', { lineHeight: 'var(--line-height-4)', letterSpacing: 'var(--letter-spacing-4)' }],
        5: ['var(--font-size-5)', { lineHeight: 'var(--line-height-5)', letterSpacing: 'var(--letter-spacing-5)' }],
        6: ['var(--font-size-6)', { lineHeight: 'var(--line-height-6)', letterSpacing: 'var(--letter-spacing-6)' }],
        7: ['var(--font-size-7)', { lineHeight: 'var(--line-height-7)', letterSpacing: 'var(--letter-spacing-7)' }],
        8: ['var(--font-size-8)', { lineHeight: 'var(--line-height-8)', letterSpacing: 'var(--letter-spacing-8)' }],
        9: ['var(--font-size-9)', { lineHeight: 'var(--line-height-9)', letterSpacing: 'var(--letter-spacing-9)' }],
      },
      fontWeight: {
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-regular)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
      },
      
      /* ============================================
         COLOR SYSTEM
         ============================================ */
      colors: {
        /* Semantic Tokens (use these!) */
        border: {
          DEFAULT: 'var(--border)',
          hover: 'var(--border-hover)',
        },
        input: {
          DEFAULT: 'var(--input)',
          hover: 'var(--input-hover)',
        },
        ring: 'var(--ring)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        overlay: 'var(--overlay)',
        
        primary: {
          DEFAULT: 'var(--primary)',
          hover: 'var(--primary-hover)',
          active: 'var(--primary-active)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          hover: 'var(--secondary-hover)',
          foreground: 'var(--secondary-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          hover: 'var(--destructive-hover)',
          foreground: 'var(--destructive-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          hover: 'var(--muted-hover)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover: 'var(--accent-hover)',
          foreground: 'var(--accent-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        
        /* Color Scales (advanced use) */
        gray: {
          1: 'var(--gray-1)',
          2: 'var(--gray-2)',
          3: 'var(--gray-3)',
          4: 'var(--gray-4)',
          5: 'var(--gray-5)',
          6: 'var(--gray-6)',
          7: 'var(--gray-7)',
          8: 'var(--gray-8)',
          9: 'var(--gray-9)',
          10: 'var(--gray-10)',
          11: 'var(--gray-11)',
          12: 'var(--gray-12)',
          a1: 'var(--gray-a1)',
          a2: 'var(--gray-a2)',
          a3: 'var(--gray-a3)',
          a4: 'var(--gray-a4)',
          a5: 'var(--gray-a5)',
          a6: 'var(--gray-a6)',
          a7: 'var(--gray-a7)',
          a8: 'var(--gray-a8)',
          a9: 'var(--gray-a9)',
          a10: 'var(--gray-a10)',
          a11: 'var(--gray-a11)',
          a12: 'var(--gray-a12)',
        },
        'accent-scale': {
          1: 'var(--accent-1)',
          2: 'var(--accent-2)',
          3: 'var(--accent-3)',
          4: 'var(--accent-4)',
          5: 'var(--accent-5)',
          6: 'var(--accent-6)',
          7: 'var(--accent-7)',
          8: 'var(--accent-8)',
          9: 'var(--accent-9)',
          10: 'var(--accent-10)',
          11: 'var(--accent-11)',
          12: 'var(--accent-12)',
          a1: 'var(--accent-a1)',
          a2: 'var(--accent-a2)',
          a3: 'var(--accent-a3)',
          a4: 'var(--accent-a4)',
          a5: 'var(--accent-a5)',
          a6: 'var(--accent-a6)',
          a7: 'var(--accent-a7)',
          a8: 'var(--accent-a8)',
          a9: 'var(--accent-a9)',
          a10: 'var(--accent-a10)',
          a11: 'var(--accent-a11)',
          a12: 'var(--accent-a12)',
        },
        error: {
          1: 'var(--error-1)',
          2: 'var(--error-2)',
          3: 'var(--error-3)',
          4: 'var(--error-4)',
          5: 'var(--error-5)',
          6: 'var(--error-6)',
          7: 'var(--error-7)',
          8: 'var(--error-8)',
          9: 'var(--error-9)',
          10: 'var(--error-10)',
          11: 'var(--error-11)',
          12: 'var(--error-12)',
        },
        success: {
          1: 'var(--success-1)',
          2: 'var(--success-2)',
          3: 'var(--success-3)',
          4: 'var(--success-4)',
          5: 'var(--success-5)',
          6: 'var(--success-6)',
          7: 'var(--success-7)',
          8: 'var(--success-8)',
          9: 'var(--success-9)',
          10: 'var(--success-10)',
          11: 'var(--success-11)',
          12: 'var(--success-12)',
        },
        warning: {
          1: 'var(--warning-1)',
          2: 'var(--warning-2)',
          3: 'var(--warning-3)',
          4: 'var(--warning-4)',
          5: 'var(--warning-5)',
          6: 'var(--warning-6)',
          7: 'var(--warning-7)',
          8: 'var(--warning-8)',
          9: 'var(--warning-9)',
          10: 'var(--warning-10)',
          11: 'var(--warning-11)',
          12: 'var(--warning-12)',
        },
      },
      borderRadius: {
        1: 'var(--radius-1)',
        2: 'var(--radius-2)',
        3: 'var(--radius-3)',
        4: 'var(--radius-4)',
        5: 'var(--radius-5)',
        6: 'var(--radius-6)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      keyframes: {
        shimmer: {
          '100%': { transform: 'translateX(100%)' },
        },
      },
    },
  },
  plugins: [],
};
